version: "3.9"
services:
  web:
    image: who-is:latest
    build: .
    ports:
      - "8080:80"
      - "43:43"
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=whoisdb
    volumes:
      - ./Init.sql:/docker-entrypoint-initdb.d/init.sql
